---
title: "week 15"
author: "Meng Qi"
date: "2020/12/24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#source("isDsExists.R")
#install.packages("AER") #裝AER
library("AER")
data("Journals", package = "AER")
View(Journals)
journals<-Journals[,c("subs","price")]
journals$citeprice <- Journals$price/Journals$citations
summary(journals)
mm<-lm(subs ~ citeprice, data = journals)
mm
```


```{r}
plot(log(subs) ~ log(citeprice), data = journals)
class(mm)
names(mm)

mm$model
str(mm$model)
```
```{r}
plot(log(subs) ~ log(citeprice), data = journals)
```

```{r}
mm<-lm(subs ~ citeprice, data = journals)
plot(mm)

```
```{r}
nn<-plot(log(subs) ~ log(citeprice), data = journals)
abline(nn)
summary(nn)
```
```{r}
plot(log(subs) ~ log(citeprice), data = journals)
jour_lm <- lm(log(subs) ~ log(citeprice), data = journals)
abline(jour_lm)
class(jour_lm)
names(jour_lm)
str(jour_lm)
summary(jour_lm)


```

```{r}
jour_slm <- summary(jour_lm)
class(jour_slm)
names(jour_slm)
anova(jour_lm)
```

```{r}
Journals<-read.csv("Journals.csv")
journals<-Journals[,c("subs","price")]
journals$citeprice <- Journals$price/Journals$citations
journals$lsubs<-log(journals$subs)
journals$lciteprice<-log(journals$citeprice)


plot(lsubs~lciteprice,data = journals)
jour_lm<-lm(lsubs~lciteprice,data = journals)
abline(jour_lm)
anova(jour_lm)

linearHypothesis(jour_lm,"lciteprice= -0.5")



coef(jour_lm)
confint(jour_lm, level = 0.95)
predict(jour_lm, newdata = data.frame(lciteprice = c(2.11,3)), interval = "confidence")
x<-predict(jour_lm, newdata = data.frame(lciteprice = c(2.11,3)),  interval = "prediction")

mydata <- seq(from = -4, to = 2, by = 0.25)
jour_pred <- predict(jour_lm, interval = "prediction",
  newdata = data.frame(lciteprice = mydata))  
plot(lsubs ~ lciteprice, data = journals)
lines(jour_pred[, 1] ~ mydata, col = 1)    
lines(jour_pred[, 2] ~ mydata, col = 1, lty = 2)
lines(jour_pred[, 3] ~ mydata, col = 1, lty = 2)
```

```{r}



```