---
title: "week 06"
author: "Meng Qi"
date: "2020/10/22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

# **元素運算**
```{r}

x1<-T
x2<-c(F,T)
b<-x1|x2
b
##x1會變為(T,T)


```
# **邏輯函數**
```{r}
A<-c("A","B","C","D")
B<-A
C<-c("A","C","C","E")
A==B
A==C
A[A==C]
which(A==C)##位置表示
which(A!=C)

temp<-1:length(A)
temp[A!=C]

which(A!=C)
```
# **function**
```{r}
cos_sin<-function(from,to)
{
xsmp<-seq(from,to,length=100)
temp<-cos(xsmp)+2*sin(xsmp)
return(temp) ##計算結果要傳回去
}
cos_sin(-pi,2*pi)

sum<-function(x,y){
return(x+y)
}
sum(5:7,8)
```

# **畫圖**
```{r}
from<- -pi
to<- 2*pi
xsmp<-seq(from,to,length=100)
ys<-sin(xsmp)
plot(xsmp)

```

# **練習**
# 1.*隨機產生1-300個號碼*

```{r}
runif(5)
runif(5,1,300)  #產生5個1-300的號碼
as.integer(1.4) #轉換為整數
as.integer(runif(300)*300)+1  #0-299->*300->1-299->+1->1-300
as.integer(runif(20,1,300))
```

# 2.*產生亂數300個，平均值=5，標準差為2的母體*


```{r}
x<-rnorm(300,5,2)  #rnorm 為隨機變數
hist(x)
```


# 3.*抽樣本100個，計算這20個樣本的統計量*

**自己**
```{r}
y<-as.integer(runif(20,1,300))
y
summary(y)
y.sum<-summary(y)
hist(y)
print(y.sum[4])
```
**老師**
```{r}

idx<-as.integer(runif(100)*300)+1
s<-x[idx]
s.sum<-summary(s)
hist(s)
print(s)
print(s.sum[4])
s.mean<-s.sum[4]
s.sd<-sd(s)/sqrt(300)

print(s.mean)
print(s.sd)

s.conf<-c(-1.96*s.sd,1.96*s.sd)+s.mean

```

