---
title: "week 17"
author: "Meng Qi"
date: "2021/01/07"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# test
某公司宣稱生產的輪軸,直徑為5CM,標準差為1CM,如何確定是否為真?
```{r}
x<-c(3.801895,5.214785,5.445979,4.293448,7.401404,4.156799,6.029400,3.982314,3.605331,4.707879,4.087529,4.635022,5.597247,3.889285,6.268631,
6.304441,5.565396,5.380210,1.754372,5.449418)
u.test<-function(x,mu,thegma)
{  Se=thegma/sqrt(length(x))
   u=(mean(x)-mu)/Se
   p=pnorm(u)
   list(u=u, p=p)
}
rst<-u.test(x,5,1)
rst

m<-qnorm(0.975)
x <- seq(-4, 4, length=100)
hx <- dnorm(x)
plot(x,hx,"l")
rug(c(-m,rst$u,0,m))
```
```{r}
n<-pnorm(80,100,15)
n
pnorm(120,100,15)-pnorm(80,100,15)
```
# 畫圖
汽車廠商聲稱每加侖可走的里程不低於25mile,標準差2.4mile。
```{r}
u.test<-function(x,mu,thegma,alternative="twoside")
{  Se=thegma/sqrt(length(x))
   u <-(mean(x)-mu)/Se
   p <-pnorm(u)
   if(alternative=="twoside") p<-2*(1-pnorm(abs(u))) #u轉成正的,1-pnorm(abs(u))為全部扣除外面面積,*2可得兩邊的面積
   else if (alternative=="less") p<-pnorm(u)
   else p <- 1-pnorm(u)
   list(u=u, p=p)
}


b=c(22,24,21,24,23,24,23,22,21,25)
u.test(b, 25,2.4,"less")

```
# t.test
* 單樣本
* 要做均值檢定或是常態
* alternative條件要大於或是等於或小於
```{r}
x=c(50.2,49.6,51.0,50.8,50.6,49.8,51.2,49.7,51.5,50.3,51.0,50.6)
t.test(x,mu=50,alternative ="greater") 
#P-value小於0.025 範圍(0.027,0.075)
var.test1<-function(x, sigma2){
  n<-length(x)
  S2=var(x)
  df=n-1
  chi2<-df*S2/sigma2; #來自於標準常態分配的N個隨機變數，其平方和屬於chi2(n)卡方自由度為n的分配
  P<-pchisq(chi2,df)
  data.frame(var=S2, df=df, chisq2=chi2, P_value=P)
}
```
# Z test
```{r}
m<-qnorm(0.975)
x<-seq(-4,4,length=100)
hx<-dnorm(x)
plot(x,hx,"l")
rug(c(-m,0,m),col="blue")
rug(c(rst$u),col="red")

```
# var.test

```{r}
x1=c(24, 29, 39, 40, 32, 32, 31, 44, 37, 37, 50, 28, 24, 48, 25,40, 32, 34, 35, 41)
x2=c(44, 34, 36, 38, 30, 30, 35, 38, 40, 46, 38, 35, 38, 36, 38,40, 34, 37, 40, 46)
var.test(x1,x2)
x1=c(48,47,44,45,46,47,43,47,42,48)
x2=c(36,45,47,38,39,42,36,42,46,35)
var.test(x1,x2)

```

# 配對樣本的均值檢驗
* 多使用於政策檢定、醫療檢定
* 來自同一群人(樣本)檢定結果是否相同
* 如果不是配對樣本,要檢驗均值

1) 是否常態分配ks.test()峰度偏斜姓 lillie.test()
1) 是否同樣的方差,方差同值檢定:var.test()
* ex7.8 服藥前後是否有差異
```{r}
before = c(94.5,101,110,103.5,97,88.5,96.5,101,104,116.5)
after = c(85,89.5,101.5,96,86,80.5,87,93.5,93,102)
t.test(before,after,paired=T)

```
# ks.test
準確率比較低
```{r}
ks.test(rnorm(100, mean = 5, sd = 3),"pnorm",mean=5,sd=3)#來自常態
ks.test(rnorm(100, mean = 5, sd = 3),rnorm(100, mean = 5, sd = 3))#來自同一母體(差一點)
```
# 只能檢定是否來自常態分配
```{r}
#install.packages(nortest)
#library(nortest)
#lillie.test(rnorm(100, mean = 5, sd = 3))
```
# 畫區域圖
```{r}
x<-seq(0,40)
y<-dchisq(x,df=10)
i<-x>=20
plot(x,y,"l")

polygon(x[i],y[i],col = "red",border = NA)


```

```{r}
x<-seq(0,40)
y<-dchisq(x,df=10)
i<-x>=20
plot(x,y,"l")

polygon(c(x[i],20),c(y[i],0),col = "red", border = NA)
```


#檢定總結

有母體平均或是方差
* Z-test
* chi-2

沒有母體平均或是方差
* t-test
* F-test







