---
title: "week 16"
author: "Meng Qi"
date: "2020/12/31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# 探索資料，畫圖分類
```{r}
head(iris)
levels(iris$Species)
table(iris$Species)
iris$Petal.Length
rep(50,3) #50這個值要重複3次
rep(c("1","2","3"),4)
rep(c("1","2","3"),c(50,50,50)) #做對應
rep(c("1","2","3"),rep(50,3))
c(rep("1",50),rep("2",50))
iris.lab<-rep(c("1","2","3"),rep(50,3))
plot(iris[,1],iris[,3],type="n")      
text(iris[,1],iris[,3],cex=0.6)       
plot(iris[,1],iris[,3],type="n") 
text(iris[,1],iris[,3],iris.lab,cex=0.7)

par(mfrow=c(1,1)) 
pairs(iris)
```
# boxplot
```{r}
x=c(5,5,13,7,11,11,9,8,9)
y=c(11,8,4,5,9,5,10,5,4,10)
boxplot(x,y)  # x畫一個，y畫一個
```
```{r}
d=c(5,5,5,13,7,11,11,9,8,9,11,8,4,5,9,5,10,5,4,10)
g=c(1,1,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,2,2) #分類。凡是類別為1的畫一個圖，類別為2的畫一個圖
boxplot(d~g)
```
```{r}
head(PlantGrowth)
attach(PlantGrowth)
table(PlantGrowth$group) #三組10，30個樣本
summary(PlantGrowth)
length(PlantGrowth)
length(PlantGrowth$group)
length(group) #也可以直接打，建議當資料很多不要直接打
boxplot(weight~group)
stripchart(weight~group)
plot(weight,group)
par(mfrow=c(1,2))

stripchart(weight~group) #與下相同
plot(weight,group) #與上相同

dotchart(weight)
weight
```
```{r}
library(MASS)
data(Cars93)
dim(Cars93)
attach(Cars93)
names(Cars93)
price=cut(Price,c(0,12,20,max(Price))) 
class(price)
summary(price) #max為61.9
levels(price) #分組為0-12，12-20，20-61.9
levels(price)<-c("便宜","普通","昂貴")
levels(price)
table(price)

levels(price)=c("cheap","okay","expensive")
table(price)

mpg=cut(MPG.highway,c(0,20,30,max(MPG.highway)))
table(mpg)
levels(mpg)=c("gas guzzler","oky","miser")
table(mpg)
table(Type)

table(price,Type)
table(price,mpg)
table(price,Type,mpg)

par(mfrow=c(1,2))
barplot(table(price,Type))
barplot(table(price,Type),beside=T)
```
```{r}
r2=rnorm(100)
f2=factor(rep(1:5,20))
par(mfrow=c(1,1))
stripchart(r2~f2)
length(r2)
length(f2)
par(mfrow=c(1,1))
dotchart(PlantGrowth$weight,groups=PlantGrowth$group)

```
```{r}
#install.packages("UsingR")
library(UsingR)
data(ewr)


EDA <- function (x)
{ 
  par(mfrow=c(2,2))              
  hist(x)                        
  dotchart(x)                    
  boxplot(x,horizontal=T)        
  qqnorm(x);qqline(x)            
  par(mfrow=c(1,1))              
}

data(exec.pay) 
mean(exec.pay)
summary(exec.pay)
boxplot(exec.pay)

mean(exec.pay,trim=0.1)
EDA(exec.pay)

EDA <- function (x)
{ 
  par(mfrow=c(2,2))              
  hist(x)                        
  dotchart(x)                    
  boxplot(x,horizontal=T)        
  qqnorm(x);qqline(x)            
  par(mfrow=c(1,1))              
}

```
```{r}
source("EDA.R")
pay=c(11,19,14,22,14,28,13,81,12,43,11,16,31,16,23,42,22,26,17,22,13,27,108,16,43,82,14,11,51,76,28,66,29,14,14,65,37,16,37,35,39,27,14,17,13,38,28,40,85,32,25,26,16,12,54,40,18,27,16,14,33,29,77,50,19,34)
EDA(pay)
```
```{r}
rr<-runif(1000)
MS=read.csv("mathstat.csv",header=T)
qqplot(MS$maths,rr)
qqplot(MS$stats,rr)
```
```{r}
r1<-runif(1000)
r2<-runif(2000)
qqplot(r1,r2)
```








